package service.edge;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author joseph
 */
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
 import java.sql.*;
import java.text.SimpleDateFormat;
public class RegisterForm extends javax.swing.JFrame {

    /**
     * Creates new form RegisterForm
     */
    public RegisterForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setBackground(new Color(0,0,0,0));
          jPanel1.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_FN = new javax.swing.JTextField();
        jPasswordField_PASS = new javax.swing.JPasswordField();
        jButton_Register_ = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_LN = new javax.swing.JTextField();
        jTextField_UN = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPasswordField_REPASS = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jDateChooser_BDATE = new com.toedter.calendar.JDateChooser();
        jSeparator6 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 260, 20));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 18, 50));
        jLabel5.setText("Password");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, 30));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 18, 50));
        jLabel6.setText("Username");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jTextField_FN.setFont(new java.awt.Font("Trebuchet MS", 0, 17)); // NOI18N
        jTextField_FN.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_FN.setText("Enter First Name");
        jTextField_FN.setBorder(null);
        jTextField_FN.setOpaque(false);
        jTextField_FN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_FNMouseClicked(evt);
            }
        });
        jPanel2.add(jTextField_FN, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 260, 32));

        jPasswordField_PASS.setFont(new java.awt.Font("Trebuchet MS", 0, 17)); // NOI18N
        jPasswordField_PASS.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField_PASS.setText("Enter Password");
        jPasswordField_PASS.setBorder(null);
        jPasswordField_PASS.setOpaque(false);
        jPasswordField_PASS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField_PASSMouseClicked(evt);
            }
        });
        jPanel2.add(jPasswordField_PASS, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 260, 30));

        jButton_Register_.setBackground(new java.awt.Color(0, 18, 50));
        jButton_Register_.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jButton_Register_.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Register_.setText("Sign Up");
        jButton_Register_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Register_ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_Register_, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 140, 40));

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 18, 50));
        jLabel7.setText("First Name");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 18, 50));
        jLabel8.setText("Last Name");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 90, 20));

        jTextField_LN.setFont(new java.awt.Font("Trebuchet MS", 0, 17)); // NOI18N
        jTextField_LN.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_LN.setText("Enter Last Name");
        jTextField_LN.setBorder(null);
        jTextField_LN.setOpaque(false);
        jTextField_LN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_LNMouseClicked(evt);
            }
        });
        jPanel2.add(jTextField_LN, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 260, 33));

        jTextField_UN.setFont(new java.awt.Font("Trebuchet MS", 0, 17)); // NOI18N
        jTextField_UN.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_UN.setText("Enter UserName");
        jTextField_UN.setBorder(null);
        jTextField_UN.setOpaque(false);
        jTextField_UN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_UNMouseClicked(evt);
            }
        });
        jPanel2.add(jTextField_UN, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 260, 40));

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 18, 50));
        jLabel9.setText("Retpye Pass");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jPasswordField_REPASS.setFont(new java.awt.Font("Trebuchet MS", 0, 17)); // NOI18N
        jPasswordField_REPASS.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField_REPASS.setText("esdjffffnfnfsd");
        jPasswordField_REPASS.setBorder(null);
        jPasswordField_REPASS.setOpaque(false);
        jPasswordField_REPASS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField_REPASSMouseClicked(evt);
            }
        });
        jPanel2.add(jPasswordField_REPASS, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 260, 30));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 260, 20));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 260, 20));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 260, 20));

        jLabel11.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 18, 50));
        jLabel11.setText("BirthDate");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        jDateChooser_BDATE.setBackground(new java.awt.Color(102, 102, 102));
        jDateChooser_BDATE.setForeground(new java.awt.Color(153, 153, 153));
        jDateChooser_BDATE.setOpaque(false);
        jPanel2.add(jDateChooser_BDATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 260, 30));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 260, 20));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/outline_navigate_before_black_24dp.png"))); // NOI18N
        jButton1.setText("Back");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 90, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 450, 490));

        jPanel3.setBackground(new java.awt.Color(0, 18, 50));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/truck.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 310, 200));

        jLabel2.setFont(new java.awt.Font("BankGothic Md BT", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Closer Than Anywhere ...");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 280, 70));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 870, 390));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public boolean checkUsername(String username)
    {
        PreparedStatement ps;
        ResultSet rs;
        boolean checkUser = false;
        String query = "SELECT * FROM `the_app_users` WHERE `u_uname` =?";
        
        try {
            ps = MyConnection.getConnection().prepareStatement(query);
            ps.setString(1, username);
            
            rs = ps.executeQuery();
            
            if(rs.next())
            {
                checkUser = true;
            }
        } catch (SQLException ex) {
            System.out.print("SQL error in Check Username");
//            Logger.getLogger(RegisterForm.class.getName()).log(Level.SEVERE, null, ex);
        }
     
         return checkUser;
    }

    private void jButton_Register_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Register_ActionPerformed

        String fname = jTextField_FN.getText();
        String lname = jTextField_LN.getText();
        String uname = jTextField_UN.getText();
        String pass = String.valueOf(jPasswordField_PASS.getPassword());
        String re_pass = String.valueOf(jPasswordField_REPASS.getPassword());
        String bdate = null;


        if(uname.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Add A Username");
        }

        else if(pass.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Add A Password");
        }
        else if(!pass.equals(re_pass))
        {
            JOptionPane.showMessageDialog(null, "Retype The Password Again");
        }

        else if(checkUsername(uname))
        {
            JOptionPane.showMessageDialog(null, "This Username Already Exist");
        }

        else{

            if(jDateChooser_BDATE.getDate() != null)
            {
                SimpleDateFormat dateformat = new SimpleDateFormat("yyyy-MM-dd");
                bdate = dateformat.format(jDateChooser_BDATE.getDate());
            }

            PreparedStatement ps;
            String query = "INSERT INTO `the_app_users`(`u_fname`, `u_lname`, `u_uname`, `u_pass`, `u_bdate`) VALUES (?,?,?,?,?)";

            try {
                ps = MyConnection.getConnection().prepareStatement(query);

                ps.setString(1, fname);
                ps.setString(2, lname);
                ps.setString(3, uname);
                ps.setString(4, pass);

                if(bdate != null)
                {
                    ps.setString(5, bdate);
                }else{
                    ps.setNull(5, 0);
                }
                

                if(ps.executeUpdate() > 0)
                {
                    JOptionPane.showMessageDialog(null, "New User Add");
                }
                LoginForm lgf = new LoginForm();
                lgf.setVisible(true);
                lgf.pack();
                lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                this.dispose();

            } catch (SQLException ex) {
                System.out.print(ex.getMessage()+"SQL error in jbutton_Register");
                            
            }
        }
    }//GEN-LAST:event_jButton_Register_ActionPerformed

    private void jTextField_FNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_FNMouseClicked
        // TODO add your handling code here:
        jTextField_FN.setText("");
    }//GEN-LAST:event_jTextField_FNMouseClicked

    private void jTextField_LNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_LNMouseClicked
        // TODO add your handling code here:
        jTextField_LN.setText("");
    }//GEN-LAST:event_jTextField_LNMouseClicked

    private void jTextField_UNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_UNMouseClicked
        // TODO add your handling code here:
        jTextField_UN.setText("");
    }//GEN-LAST:event_jTextField_UNMouseClicked

    private void jPasswordField_PASSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField_PASSMouseClicked
        // TODO add your handling code here:
        jPasswordField_PASS.setText("");
    }//GEN-LAST:event_jPasswordField_PASSMouseClicked

    private void jPasswordField_REPASSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField_REPASSMouseClicked
        // TODO add your handling code here:
        jPasswordField_REPASS.setText("");
    }//GEN-LAST:event_jPasswordField_REPASSMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        LoginForm lgf = new LoginForm();
                lgf.setVisible(true);
                lgf.pack();
                lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_Register_;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser_BDATE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField_PASS;
    private javax.swing.JPasswordField jPasswordField_REPASS;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField jTextField_FN;
    private javax.swing.JTextField jTextField_LN;
    private javax.swing.JTextField jTextField_UN;
    // End of variables declaration//GEN-END:variables
}
