/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package service.edge;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author joseph
 */
public class Summary extends javax.swing.JFrame {

    /**
     * Creates new form Summary
     */ String name;
    public Summary() {
        initComponents();
    }
    public Summary(String suname) {
        initComponents();
        this.name=suname;
        jLabel_UN.setText(name);
        jLabel_UN.setFont(new java.awt.Font("Berlin Sans FB", 0, 16));
        jLabel_loc.setFont(new java.awt.Font("Berlin Sans FB", 0, 16));
        jLabel_cat.setFont(new java.awt.Font("Berlin Sans FB", 0, 16));
        jLabel_provider.setFont(new java.awt.Font("Berlin Sans FB", 0, 14));
        jTextArea_problem.setFont(new java.awt.Font("Berlin Sans FB", 0, 14));
        this.setLocationRelativeTo(null);
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wait = new javax.swing.JLayeredPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel_UN = new javax.swing.JLabel();
        btn_order = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_problem = new javax.swing.JTextArea();
        jLabel_loc = new javax.swing.JLabel();
        jLabel_cat = new javax.swing.JLabel();
        jLabel_provider = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        wait.setBackground(new java.awt.Color(0, 0, 153));
        wait.setForeground(new java.awt.Color(0, 0, 102));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(java.awt.Color.lightGray);
        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 18, 50));
        jLabel1.setText("Problem");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 90, 40));

        jSeparator1.setBackground(java.awt.Color.lightGray);
        jSeparator1.setForeground(new java.awt.Color(0, 18, 50));
        jPanel5.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 170, 10));

        jLabel2.setBackground(java.awt.Color.lightGray);
        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 18, 50));
        jLabel2.setText("ORDER SUMMARY");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 240, 40));

        jLabel5.setBackground(java.awt.Color.lightGray);
        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 18, 50));
        jLabel5.setText("Username");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 100, 40));

        jLabel6.setBackground(java.awt.Color.lightGray);
        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 18, 50));
        jLabel6.setText("Location ");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 80, 40));

        jLabel4.setBackground(java.awt.Color.lightGray);
        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 18, 50));
        jLabel4.setText("Category ");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 100, 40));

        jLabel12.setBackground(java.awt.Color.lightGray);
        jLabel12.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 18, 50));
        jLabel12.setText("Provider ");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 70, 40));

        jLabel_UN.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel_UN.setForeground(new java.awt.Color(0, 18, 50));
        jLabel_UN.setText("Set Name");
        jPanel5.add(jLabel_UN, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 150, 40));

        btn_order.setBackground(new java.awt.Color(0, 18, 50));
        btn_order.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        btn_order.setForeground(new java.awt.Color(255, 255, 255));
        btn_order.setText("Place Order");
        btn_order.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_orderMouseClicked(evt);
            }
        });
        jPanel5.add(btn_order, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 120, 30));

        jTextArea_problem.setColumns(20);
        jTextArea_problem.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jTextArea_problem.setForeground(new java.awt.Color(204, 204, 204));
        jTextArea_problem.setRows(5);
        jTextArea_problem.setText("(Optional)");
        jTextArea_problem.setBorder(null);
        jTextArea_problem.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextArea_problem.setSelectionColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTextArea_problem);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 210, 120));

        jLabel_loc.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel_loc.setForeground(new java.awt.Color(0, 18, 50));
        jLabel_loc.setText("Set Name");
        jPanel5.add(jLabel_loc, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 220, 40));

        jLabel_cat.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel_cat.setForeground(new java.awt.Color(0, 18, 50));
        jLabel_cat.setText("Set Name");
        jPanel5.add(jLabel_cat, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 230, 40));

        jLabel_provider.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel_provider.setForeground(new java.awt.Color(0, 18, 50));
        jLabel_provider.setText("Set Name");
        jPanel5.add(jLabel_provider, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 240, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mail.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, -40, 760, 560));

        wait.setLayer(jPanel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout waitLayout = new javax.swing.GroupLayout(wait);
        wait.setLayout(waitLayout);
        waitLayout.setHorizontalGroup(
            waitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
            .addGroup(waitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        waitLayout.setVerticalGroup(
            waitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
            .addGroup(waitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(wait, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 430, 520));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\joseph\\Pictures\\screen.png")); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_orderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_orderMouseClicked
        // TODO add your handling code here:
        PreparedStatement ps;
        ResultSet rs;
         String name=jLabel_UN.getText();
         String location=jLabel_loc.getText();
         String category=jLabel_cat.getText();
         String provider=jLabel_provider.getText();
         String problem=jTextArea_problem.getText();

        String query = "INSERT INTO `order`(`od_uname`, `od_location`, `od_category`, `od_provider`, `od_problem`) VALUES (?,?,?,?,?)";


        try {
            ps = MyConnection.getConnection().prepareStatement(query);

            ps.setString(1, name);
            ps.setString(2, location);
            ps.setString(3, category);
            ps.setString(4, provider);
            ps.setString(5, problem);

             if(ps.executeUpdate() > 0)
                {
                    JOptionPane.showMessageDialog(null, "Order Placed !");
                }

        } catch (SQLException ex) {
            System.out.print("SQL error in j button _order" +ex.getMessage());
        }
        HOME_JFrame mf = new HOME_JFrame(name);
                mf.setVisible(true);
                mf.pack();
                this.dispose();
    }//GEN-LAST:event_btn_orderMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Summary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Summary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Summary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Summary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Summary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_order;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel_UN;
    public javax.swing.JLabel jLabel_cat;
    public javax.swing.JLabel jLabel_loc;
    public javax.swing.JLabel jLabel_provider;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea_problem;
    private javax.swing.JLayeredPane wait;
    // End of variables declaration//GEN-END:variables
}
